function ActionBar({ onReassess, onClear, result }) {

  const handleExport = () => {
    if (!result) return

    const factors = result.factors
      .map(f => `${f.name}: ${f.value} — ${f.detail}`)
      .join('\n')

    const news = result.news
      .map(n => `• [${n.sentiment.toUpperCase()}] ${n.headline} — ${n.source}`)
      .join('\n')

    const report = `
SUPPLIER ONBOARDING ASSESSMENT REPORT
======================================
Supplier  : ${result.supplierName}
Country   : ${result.country}
Industry  : ${result.industry}
Verdict   : ${result.verdict}
Risk Score: ${result.overallScore}/100
Assessed  : ${new Date().toLocaleString()}

EXECUTIVE SUMMARY
-----------------
${result.summary}

RISK FACTOR BREAKDOWN
---------------------
${factors}

LATEST NEWS & SIGNALS
---------------------
${news}

--- Generated by SupplierIQ ---
    `.trim()

    const blob = new Blob([report], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${result.supplierName.replace(/\s+/g, '_')}_SupplierIQ.txt`
    a.click()
  }

  const btnBase = {
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
    padding: '10px 18px',
    borderRadius: '8px',
    fontFamily: 'Syne, sans-serif',
    fontWeight: '600',
    fontSize: '13px',
    cursor: 'pointer',
    border: '1px solid var(--border2)',
    background: 'var(--surface2)',
    color: 'var(--text2)'
  }

  return (
    <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>

      <button
        onClick={onReassess}
        style={{
          ...btnBase,
          background: 'linear-gradient(135deg, var(--accent), var(--accent2))',
          border: 'none',
          color: '#fff'
        }}
      >
        ↻ Re-assess
      </button>

      <button onClick={handleExport} style={btnBase}>
        ⬇ Export Report
      </button>

      <button onClick={onClear} style={btnBase}>
        ✕ Clear
      </button>

    </div>
  )
}

export default ActionBar